language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - CONF=release
        - GENERATOR="Unix Makefiles"
        - TESTS="./tests"
    - os: linux
      compiler: gcc
      env:
        - CONF=debug
        - GENERATOR="Unix Makefiles"
        - TESTS="./tests"
        - GCOV_FLAGS='--coverage'
      after_success:
        - pip install --user cpp-coveralls
        - coveralls -r .. --gcov-options '\-lp'
    - os: osx
      osx_image: xcode10.2
      env:
        - CONF=release
        - GENERATOR="Unix Makefiles"
        - TESTS="./tests"
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017"
        - TESTS="./Debug/tests.exe"

script:
  - mkdir -p build
  - cd build
  - cmake -G "$GENERATOR" -DCMAKE_BUILD_TYPE=$CONF -DCMAKE_CXX_FLAGS="$GCOV_FLAGS" -DCMAKE_EXE_LINKER_FLAGS=$GCOV_FLAGS ..
  - cmake --build .
  - ls
  - $TESTS
