language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - GENERATOR="Unix Makefiles"
        - TESTS="./tests"
    - os: osx
      osx_image: xcode10.2
      env:
        - GENERATOR="Unix Makefiles"
        - TESTS="./tests"
    - os: windows
      env:
        - GENERATOR="Visual Studio 15 2017"
        - TESTS="./Debug/tests.exe"

script:
  - mkdir -p build
  - cd build
  - cmake -G "$GENERATOR" ..
  - cmake --build .
  - ls
  - $TESTS
