name: CMake

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        cxx: [g++-8, g++-9, g++-10, clang++-8, clang++-9, clang++-10]
        build_type: [Debug, Release]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure
      shell: bash
      env:
        CXX: ${{matrix.cxx}}
      working-directory: ${{github.workspace}}/build
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C ${{matrix.build_type}}
