name: linux

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        cxx: [g++-10, clang++-10]
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-9

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure
        shell: bash
        working-directory: ${{github.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
        run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Test
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{matrix.build_type}}
